on:
  push:
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
  test:
    runs-on: ubuntu-latest
    name: test
    needs: lint
    steps:
      - name: Set up Go v1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: test
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action ${{ secrets.ASD }}
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: systemctl restart fitbuddy-bot